apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-server-jks
data:
  server.keystore.jks: {{ .Files.Get "conf/kafka.server.keystore.jks" | b64enc}}
  server.truststore.jks: {{ .Files.Get "conf/kafka.server.truststore.jks" | b64enc}}
