apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-headless
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
    - name: tcp-client
      port: 9092
    - name: tcp-controller
      port: 9093
    - name: tcp-internal
      port: 9094     
  clusterIP: None 
  selector:
    app: {{ .Release.Name }}
  